spring.application.name=recipelibrary

spring.mongodb.host=${MONGO_HOST}
spring.mongodb.port=${MONGO_PORT}
spring.mongodb.database=${MONGO_DB}
spring.mongodb.username=${MONGO_USER}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.authentication-database=admin

spring.web.error.include-message=always
